services:
  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.project=erpnext"
      - "traefik.http.routers.erpnext.rule=Host(`${SITE_NAME}`)"
      - "traefik.http.routers.erpnext.entrypoints=websecure"
      - "traefik.http.routers.erpnext.tls=true"
      - "traefik.http.services.erpnext.loadbalancer.server.port=8080"
    networks:
      - traefik-local
      - erpnext-internal

networks:
  traefik-local:
    name: traefik-local
    external: true
